apiVersion: v2
name: trino
description: Fast distributed SQL query engine for big data
type: application
version: 1.0.0
appVersion: "431"

keywords:
  - trino
  - presto
  - sql
  - query-engine
  - lakehouse

home: https://github.com/bifrostdata/bifrost-core
sources:
  - https://github.com/trinodb/trino
  - https://github.com/trinodb/charts

maintainers:
  - name: Bifrost Team
    email: team@bifrost.dev

dependencies:
  - name: trino
    version: "0.19.0"
    repository: https://trinodb.github.io/charts
